### ISSUE TITLE
can't build UI in ubuntu 14.04

### ISSUE THREAD

**Issue by zezhou** [yse/easy_profiler#147]
I use `cmake -DCMAKE_BUILD_TYPE="Release" ..` and it's ok.
then I use `make` command, and it run failed.

[ 30%] Building CXX object profiler_gui/CMakeFiles/profiler_gui.dir/arbitrary_value_inspector.cpp.o
In file included from easy_profiler/profiler_gui/dialog.h:55:0,
                 fromeasy_profiler/profiler_gui/arbitrary_value_inspector.cpp:79:
easy_profiler/profiler_gui/window_header.h:87:19: error: ISO C++ forbids declaration of 'Q_FLAG' with no type [-fpermissive]
     Q_FLAG(Buttons)
                   ^
easy_profiler/profiler_gui/window_header.h:87:19: error: expected ';' at end of member declaration
make[2]: *** [profiler_gui/CMakeFiles/profiler_gui.dir/arbitrary_value_inspector.cpp.o] Error 1
make[1]: *** [profiler_gui/CMakeFiles/profiler_gui.dir/all] Error 2
make: *** [all] Error 2

I used to think it's gcc/qt version's problem, but after I upgrade gcc/qt, it still don't work.

gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~14.04) 
Using Qt version 5.9.1 in /opt/Qt5.9.1/5.9.1/gcc_64/lib

I don't know what I can do now  to make it work.

**Comment by cas4ey** [comment]
Hi @zezhou 

Please, try to replace `Q_DECLARE_FLAGS(Buttons, Button)` at `profiler_gui/window_header.h:86` with `using Buttons = QFlags<Button>;`. If this error still occur, try to add `#include <QObject>` (or even `#include <qobjectdefs.h>`) in the same file.

**Comment by zezhou** [comment]
@cas4ey Thanks. It solve the problem, but there still have other compile fails.

**Comment by cas4ey** [comment]
@zezhou do you mean that replacing of `Q_DECLARE_FLAGS` helped  // or including additional header ? Which one?

It would be great if you will create a pull request with fixes (or at least post them here).

**Comment by cas4ey** [comment]
> but there still have other compile fails.

Which ones?

**Comment by zezhou** [comment]
> try to replace `Q_DECLARE_FLAGS(Buttons, Button)` at `profiler_gui/window_header.h:86` with `using Buttons = QFlags<Button>;`

I try this solution, and it stop at another position: 

> easy_profiler/profiler_gui/blocks_graphics_view.cpp:80:26: fatal error: QSignalBlocker: No such file or directory
> compilation terminated.
> make[2]: *** [profiler_gui/CMakeFiles/profiler_gui.dir/blocks_graphics_view.cpp.o] Error 1
> make[1]: *** [profiler_gui/CMakeFiles/profiler_gui.dir/all] Error 2
> make: *** [all] Error 2
> 

I think it may be the qt version confliction, though I upgrade qt to 5.9.1.

**Comment by cas4ey** [comment]
Do you have Qt less than v5.3 installed at the same time?  
I think you might not set up all environment variables properly after upgrade to 5.9.1.  
Try `cmake -DCMAKE_PREFIX_PATH="<your-path-to-Qt>/lib/cmake"`  
For example, `cmake -DCMAKE_PREFIX_PATH="/opt/Qt5.9.1/5.9.1/gcc_64/lib/cmake" ..`

**Comment by zezhou** [comment]
I try this 

>  cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH="/opt/Qt5.9.1/5.9.1/gcc_64/lib/cmake" ..

and build success. thanks a lot.
